image: docker:git

services:
  - docker:dind

variables:
  IMAGE: registry.gitlab.com/lexinek/push-to-gcr
  GCR_IMAGE: eu.gcr.io/test-push-gcr-from-gitlab/php
before_script:
  - echo $CI_BUILD_TOKEN | docker login -u gitlab-ci-token registry.gitlab.com --password-stdin

build:
  stage: build
  script:
    - docker build --cache-from $IMAGE -t $IMAGE:$CI_COMMIT_SHA .
    - docker push $IMAGE

deploy:
  stage: deploy
  before_script:
    - echo $GOOGLE_CLOUD_ACCOUNT > /tmp/$CI_PIPELINE_ID.json
  script:
    - cat /tmp/$CI_PIPELINE_ID.json | docker login -u _json_key --password-stdin https://eu.gcr.io
    - docker tag $IMAGE:$CI_COMMIT_SHA $GCR_IMAGE:latest
    - docker push $GCR_IMAGE
  after_script:
    - rm /tmp/$CI_PIPELINE_ID.json
